server:
    port: 8888


payload-logging:
    tmp-path: /tmp
    filter:
        includes:
            - uris:
                - path: /get
                - path: /.*
              methods:
                - GET
        excludes:
            - uris:
                  - path: .*/foo$


# http://localhost:8888/actuator/metrics/spring.cloud.gateway.requests
management:
    endpoints:
        web:
            exposure:
                include: health,gateway,metrics
    endpoint:
        gateway:
            enabled: true
spring:
    cloud:
        gateway:
            httpclient:
                wiretap: false
            metrics:
                tags:
                    path:
                        enabled: true
                enabled: true
            routes:
                -   id: http-bin-get
                    uri: ${rewrite.backend.uri:http://localhost/get}
                    predicates:
                        - Path=/get
                -   id: vg-front
                    uri: ${rewrite.backend.uri:https://www.vg.no/}
                    predicates:
                        - Path=/vg
                    filters:
                        - StripPrefix=1
                -   id: wallpaper
                    uri: ${rewrite.backend.uri:https://upload.wikimedia.org/wikipedia/commons/c/cc/ESC_large_ISS022_ISS022-E-11387-edit_01.JPG}
                    predicates:
                        - Path=/wall
                    filters:
                        - StripPrefix=1