server:
  port: 8888

http-logging:
  auth:
    jwt:
      enabled: true
      username-claim-name: sub
      realm-claim-name: realm
    basic:
      enabled: true
      realm-header-name: x-realm
    response-header:
      enabled: true
      strip-headers: true
      realm-header: x-realm
      username-header: x-username
  capture:
    enabled: true
    memory-buffer-size: 500KB
    temp-directory: /tmp
  providers:
    #file:
    #  enabled: true
    #  pattern: '{{gateway_request_id}} {{realm_claim}} {{user_claim}} {{method}} {{path}} {{host}} {{request_headers["Content-Length"][0]}} {{status}} {{user_agent}} {{duration | numberformat("#.###") }}'
    #  body-storage-directory: /tmp/cloud-gateway/bodies
    clickhouse:
      enabled: true
      url: 'jdbc:ch://localhost:18123/default?compress=0;async_insert=1,wait_for_async_insert=0'
  matchers:
    - id: foo
      predicates:
        - Path=/nope
    - id: bar
      predicates:
        - Path=/anything/**
        - Method=POST,PUT
        - Host=localhost:8888
      log-request-body: true
      log-response-body: false
logging:
  level:
    com.ethlo.http: debug
    org.springframework.cloud.gateway: INFO

management:
  endpoints:
    web:
      exposure:
        include: 'health,gateway,metrics,clickhouse'


spring:
  cloud:
    gateway:
      filter:
        request-rate-limiter:
          enabled: true
          deny-empty-key: true
          empty-key-status-code: 403
      metrics:
        tags:
          path:
            enabled: true
        enabled: true
      routes:
        - id: http-bin-get
          uri: '${rewrite.backend.uri:https://httpbin.org/get}'
          predicates:
            - Path=/get
          filters:
            - name: CircuitBreaker
              args:
                name: upstream-down
                fallbackUri: 'forward:/upstream-down'
            - name: RequestRateLimiter
              args:
                local-rate-limiter:
                  replenish-rate: 10000
                  refresh-period: PT10s
        - id: http-bin-any
          uri: '${rewrite.backend.uri:https://httpbin.org/anything}'
          predicates:
            - Path=/anything
          filters:
            - name: CircuitBreaker
              args:
                name: upstream-down
                fallbackUri: 'forward:/upstream-down'
            - name: RequestRateLimiter
              args:
                local-rate-limiter:
                  replenish-rate: 2
                  refresh-period: 10
  web:
    resources:
      static-locations:
        - file:/static