server:
  port: 8888

logging:
  level:
    com.ethlo.http: INFO
    org.springframework.cloud.gateway: INFO

management:
  endpoints:
    web:
      exposure:
        include: health,gateway,metrics,clickhouse,refresh
spring:
  web:
    resources:
      static-locations:
        - file:/static
config-refresh:
  enabled: true
  interval: PT5S

upstream:
  interval: PT10S