version: '3'

services:
  clickhouse:
    image: yandex/clickhouse-server
    hostname: clickhouse-cloud-gateway
    container_name: clickhouse-cloud-gateway
    ports:
      - '18123:8123'
    ulimits:
      nofile:
        soft: 262144
        hard: 262144
  cloud-gateway:
    hostname: cloud-gateway
    container_name: cloud-gateway
    image: ethlocom/cloud-gateway
    environment:
      - 'JAVA_OPTS="-XX:MaxDirectMemorySize=200M"'
      - 'SPRING_CONFIG_LOCATION=/config/application.yaml'
    volumes:
      - ./config:/config
      - ./ddl/log.ddl:/docker-entrypoint-initdb.d/log.sql
    ports:
      - '6464:8888'

  grafana:
    image: grafana/grafana:latest
    environment:
      GF_INSTALL_PLUGINS: grafana-piechart-panel,grafana-worldmap-panel,grafana-clickhouse-datasource
      GF_LOG_LEVEL: debug
    ports:
    - '3000:3000'
    depends_on:
      - clickhouse