version: '3'

services:
  clickhouse:
    image: yandex/clickhouse-server
    hostname: clickhouse-cloud-gateway
    container_name: clickhouse-cloud-gateway
    volumes:
      - ./clickhouse/init_schema.sql:/docker-entrypoint-initdb.d/init_schema.sql
    ports:
      - '18123:8123'
    ulimits:
      nofile:
        soft: 262144
        hard: 262144
  cloud-gateway:
    hostname: cloud-gateway
    container_name: cloud-gateway
    image: ethlocom/cloud-gateway
    restart: unless-stopped
    environment:
      - 'JAVA_OPTS="-XX:MaxDirectMemorySize=200M"'
      - 'SPRING_CONFIG_LOCATION=/config/application.yaml'
      - "HTTPLOGGING_PROVIDERS_CLICKHOUSE_URL=jdbc:ch://clickhouse-cloud-gateway/default?compress=0;async_insert=1,wait_for_async_insert=0"
    volumes:
      - ./config:/config
      - ./static:/static
    ports:
      - '6464:8888'

  grafana:
    image: grafana/grafana:latest
    hostname: grafana
    container_name: grafana
    environment:
      GF_INSTALL_PLUGINS: grafana-piechart-panel,grafana-worldmap-panel,grafana-clickhouse-datasource, marcusolsson-json-datasource
      GF_LOG_LEVEL: info
      GF_SECURITY_ADMIN_PASSWORD: grafana
    ports:
      - '3000:3000'
    depends_on:
      - clickhouse
    volumes:
      - ./grafana/provisioning:/etc/grafana/provisioning
      - ./grafana/dashboards:/var/lib/grafana/dashboards