{
 "title": "HTTP traffic",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "By status code",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT concat('HTTP ', CAST (status as String)) as Status, count(gateway_request_id) Requests FROM \"log\" WHERE   ( timestamp  >= $__fromTime AND timestamp <= $__toTime ) GROUP BY status LIMIT 100\n"
    }
   ]
  },
  {
   "title": "Payload size overview",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT path, method, formatReadableSize(avg(request_body_size)) as avg_request_size, formatReadableSize(avg(response_body_size)) as avg_response_size, formatReadableSize(max(response_body_size)) as max_response_size FROM \"log\" WHERE   ( timestamp  >= $__fromTime AND timestamp <= $__toTime ) group by path, method LIMIT 100"
    }
   ]
  },
  {
   "title": "Latest requests",
   "type": "table",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 8 },
   "targets": [
    {
     "rawSql": "SELECT \ntimestamp as \"Time\",\ngateway_request_id as \"Request ID\", \nconcat(method, ' ', path) as Request, \nstatus as \"HTTP status\", \nroute_id as RouteId, \nroute_uri as \"Route URI\", \nformatReadableSize(request_body_size) as \"Request Body Size\",\nformatReadableSize(response_body_size) as \"Response Body Size\",\nresponse_time/1000000000 as \"Response time\" \nFROM \"log\" \nWHERE   ( timestamp  >= $__fromTime AND timestamp <= $__toTime )",
     "selectedFormat": 1
    }
   ]
  }
 ]
}