apiVersion: 1

datasources:
- name: clickhouse
  type: grafana-clickhouse-datasource
  jsonData:
    defaultDatabase: default
    port: 9000
    server: clickhouse-cloud-gateway
    username: default
  readOnly: false
  editable: true