name: Debug Docker Push

on:
  workflow_dispatch: # Allow manual triggering

jobs:
  test-push:
    runs-on: ubuntu-latest
    steps:
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Tag and Push a Test Image
        run: |
          echo "Attempting to push to ethlocom/cloud-gateway:debug-test"
          docker pull hello-world
          docker tag hello-world ethlocom/cloud-gateway:debug-test
          docker push ethlocom/cloud-gateway:debug-test